### ISSUE TITLE
Design system foundation

### ISSUE THREAD

**Issue by yauhen-karmyzau** [open-reaction-database/ord-app#25]

**Comment by yketov** [comment]
Thank you, @yauhen-karmyzau ! Done.

- 🔤 [Typography](https://www.figma.com/design/c7M9fhVn278ei9rkepI2Sm/UX-UI-Open-Reaction-Database?node-id=1059-55067&node-type=canvas&t=pmuzmyKqp7S7AeOX-11)
- 🎨 [Colors](https://www.figma.com/design/c7M9fhVn278ei9rkepI2Sm/UX-UI-Open-Reaction-Database?node-id=1045-53163&node-type=canvas&t=pmuzmyKqp7S7AeOX-11)
- 🌻 [Icons](https://www.figma.com/design/c7M9fhVn278ei9rkepI2Sm/UX-UI-Open-Reaction-Database?node-id=1068-56217&node-type=canvas&t=pmuzmyKqp7S7AeOX-11)
